### ISSUE TITLE
CSS file is not loaded

### ISSUE THREAD

**Issue by hannskie** [hannskie/hannskie.github.io#1]
When opened, the CSS file (styles.css) is not loaded. It only showed the naked view of the HTML codes (index.html).
Solution
Do either of the following:
1. Change the linked CSS file URL. `css/styles.css` to `styles.css`
2. Delete the previously uploaded CSS (and images) and create a new file inside a folder.

**Comment by NaincyKumariKnoldus** [comment]
Hello @hannskie I have solved this issue. Please review and merge my request.

**Comment by hannskie** [comment]
Done. Thank you very much!
